<?php

/*
   LOG HANDLING
   ------------

   Those constants allow to change the max log file size and the number of files
   to keep while the logs are rotated for files generated by eZ Publish
   (eZDebug) and custom log files (eZLog)

   Maximum file size in bytes of eZ Publish generated log, ie
   error.log, warning.log, notice.log and strict.log files
   Default is 200Kb

   Maximum file size in bytes of custom log file generated with eZLog class
*/
define( 'EZPUBLISH_LOG_MAX_FILE_SIZE', 3145728 );
define( 'CUSTOM_LOG_MAX_FILE_SIZE', 3145728 );

/*
    INI FILES OPTIMIZATIONS
    -----------------------
    This new setting controls whether eZINI should check if the settings have
    been updated in the *.ini-files*. If this check is disabled eZ Publish
    will always used the cached values, lowering the amount of stat-calls to
    the file system, and thus increasing performance.

    Set EZP_INI_FILEMTIME_CHECK constant to false to improve performance by
    not checking modified time on ini files.
    You can also set it to the name of an ini file you still want to check
    modified time for. For example, set it to 'site.ini' to make the system
    still check if that file has been modified, while ignoring changes for
    any other file.

    Note that independently of this setting, new INI override files will NEVER
    be found automatically. You will need to clear at least the INI cache
    when a new INI file override is added to the structure. Note that new files
    are not affected, but this is an edge situation.
*/
define( 'EZP_INI_FILEMTIME_CHECK', false );

/*
   ImageMagick thread limit
   @see http://share.ez.no/forums/install-configuration/imagemagick-causes-high-server-load-when-opening-gallery
   @see http://www.daniloaz.com/en/617/systems/high-cpu-load-when-converting-images-with-imagemagick/
*/
putenv( "MAGICK_THREAD_LIMIT=1" );
